### ISSUE TITLE
Omeka S 3.x Compatibility

### ISSUE THREAD

**Issue by cscottjames** [Neo-Inspiration/Omeka-S-SimpleCarousel#5]
I edited the theme.ini file to try to make the module compatible with the latest major version upgrade of Omeka.

I'm getting this error now when I try to add new pages to my exhibit sites:

TypeError
Argument 1 passed to SimpleCarousel\Site\BlockLayout\Carousel::__construct() must be an instance of Zend\Form\FormElementManager, instance of Laminas\Form\FormElementManager\FormElementManagerV3Polyfill given, called in /var/www/omeka-s/modules/SimpleCarousel/src/Service/BlockLayout/CarouselFactory.php on line 14

Details:

TypeError: Argument 1 passed to SimpleCarousel\Site\BlockLayout\Carousel::__construct() must be an instance of Zend\Form\FormElementManager, instance of Laminas\Form\FormElementManager\FormElementManagerV3Polyfill given, called in /var/www/omeka-s/modules/SimpleCarousel/src/Service/BlockLayout/CarouselFactory.php on line 14 and defined in /var/www/omeka-s/modules/SimpleCarousel/src/Site/BlockLayout/Carousel.php:30
Stack trace:
#0 /var/www/omeka-s/modules/SimpleCarousel/src/Service/BlockLayout/CarouselFactory.php(14): SimpleCarousel\Site\BlockLayout\Carousel->__construct()
#1 /var/www/omeka-s/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(765): SimpleCarousel\Service\BlockLayout\CarouselFactory->__invoke()
#2 /var/www/omeka-s/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(201): Laminas\ServiceManager\ServiceManager->doCreate()
#3 /var/www/omeka-s/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(153): Laminas\ServiceManager\ServiceManager->get()
#4 /var/www/omeka-s/application/src/Site/BlockLayout/Manager.php(16): Laminas\ServiceManager\AbstractPluginManager->get()
#5 /var/www/omeka-s/application/src/View/Helper/BlockLayout.php(57): Omeka\Site\BlockLayout\Manager->get()
#6 /var/www/omeka-s/application/view/omeka/site-admin/page/edit.phtml(8): Omeka\View\Helper\BlockLayout->prepareForm()
#7 /var/www/omeka-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/var/www/omeka-...')
#8 /var/www/omeka-s/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render()
#9 /var/www/omeka-s/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render()
#10 /var/www/omeka-s/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren()
#11 /var/www/omeka-s/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render()
#12 /var/www/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render()
#13 /var/www/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners()
#14 /var/www/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent()
#15 /var/www/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest()
#16 /var/www/omeka-s/index.php(21): Laminas\Mvc\Application->run()
#17 {main}

**Comment by m-art-in** [comment]
I am also working on the problem of getting the module to run under Omeka 3.0. The Zend framework is no longer supported, so the corresponding Laminas packages have to be used. I am hopeful to be able to provide a working version.

**Comment by m-art-in** [comment]
my code is running, just made a pull request:
https://github.com/Neo-Inspiration/Omeka-S-SimpleCarousel/pull/6

**Comment by mcyzyk** [comment]
Hope this happens soon!  I'm in the process of upgrading Omeka-S and all our Simple Carousels are broken.  Thanks in advance for fixing in 3.0+.

**Comment by m-art-in** [comment]
Please feel free to test my code. If the actual developer of this module does not includes my pull, I will release my own version of the module. But a while I still wait.

**Comment by mcyzyk** [comment]
All working well with your code on Omeka-S 3.x.  Thanks!

**Comment by m-art-in** [comment]
Great! Hope the pull request will accepted soon and merged into master.
